export default {
 SPLASH = "SPLASH";
 SIGN_IN = "SIGN_IN";
 SIGN_UP = "SIGN_UP";
 FORGOT_PASSSWORD = "FORGOT_PASSSWORD";
 CHANGE_PASSWORD = "CHANGE_PASSWORD";
 CHAT_MEMBER = "CHAT_MEMBER";
 CHAT = "CHAT";
 NOTIFICATION = "NOTIFICATION";
 PROFILE = "PROFILE";
 SETTINGS = "SETTINGS";
 EDIT_PROFILE = "EDIT_PROFILE";
 SWIPE_UP = "SWIPE_UP";
 SEARCHFRIENDS = "SEARCHFRIENDS";
 CONTACTS = "CONTACTS";
 MYACCOUNT = "MYACCOUNT";
 SIGNINWELCOME = "SIGNINWELCOME";
}